//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game2048.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmrGamer
    {
        public gmrGamer()
        {
            this.gmrResults = new HashSet<gmrResult>();
        }
    
        public System.Guid gmrGamerId { get; set; }
        public string gmrGamerName { get; set; }
    
        public virtual ICollection<gmrResult> gmrResults { get; set; }
    }
}
