//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game2048.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmrResult
    {
        public int gmrResultId { get; set; }
        public System.Guid gmrGamerId { get; set; }
        public long gmrResultGamerScore { get; set; }
        public int gmrResultGamerBiggestTile { get; set; }
        public System.DateTime gmrResultDateTime { get; set; }
    
        public virtual gmrGamer gmrGamer { get; set; }
    }
}
